<a href="https://colab.research.google.com/github/Huzaifa3242/Deep-Learning-Practice/blob/main/Pytorch_pipelining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.drop(["id","Unnamed: 32"],inplace=True,axis=1)

In [ ]:
df.shape

(569, 31)

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_train

array([[ 1.30240196, -0.37968872,  1.33187618, ...,  1.89238509,
         1.4627228 ,  0.41611577],
       [ 1.60006393,  0.48537108,  1.5944043 , ...,  1.97215917,
         1.1628252 ,  0.18543704],
       [-0.72398914, -0.03840485, -0.73084477, ..., -0.7334094 ,
         0.23088536, -0.07063256],
       ...,
       [ 0.98470505,  0.0279559 ,  0.97350446, ...,  1.21890777,
         0.05836362, -0.29590898],
       [-0.81271531,  0.17963762, -0.75084691, ..., -0.32686842,
         0.10189715, -0.75942737],
       [-0.11721667, -0.74230282, -0.16245055, ..., -0.68385743,
         0.69524293, -0.38558736]])

In [ ]:
Y_train

45     M
2      M
420    B
351    M
432    M
      ..
362    B
366    M
201    M
288    B
374    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder=LabelEncoder()
Y_train=encoder.fit_transform(Y_train)
Y_test=encoder.transform(Y_test)

In [ ]:
Y_train

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(Y_train)
y_test_tensor = torch.from_numpy(Y_test)

In [ ]:
X_train_tensor

tensor([[ 1.3024, -0.3797,  1.3319,  ...,  1.8924,  1.4627,  0.4161],
        [ 1.6001,  0.4854,  1.5944,  ...,  1.9722,  1.1628,  0.1854],
        [-0.7240, -0.0384, -0.7308,  ..., -0.7334,  0.2309, -0.0706],
        ...,
        [ 0.9847,  0.0280,  0.9735,  ...,  1.2189,  0.0584, -0.2959],
        [-0.8127,  0.1796, -0.7508,  ..., -0.3269,  0.1019, -0.7594],
        [-0.1172, -0.7423, -0.1625,  ..., -0.6839,  0.6952, -0.3856]],
       dtype=torch.float64)

**Model definition**

In [ ]:
class PytorchNN():

  def __init__(self,X):
    with torch.no_grad():


     self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
     self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights) + self.bias
    y_pred=torch.sigmoid(z)
    return y_pred



  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss




In [ ]:
learning_rate=0.1
epochs=30

**Training Pipeline**

In [ ]:
# model creation
model=PytorchNN(X_train_tensor)


for epoch in range(epochs):

  # forward pass
  y_pred=model.forward(X_train_tensor)

  # loss calculate
  loss= model.loss_function(y_pred,y_train_tensor)
  # backward pass
  loss.backward()

  # updating params
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()


  print(f'Epoch: {epoch + 1} , Loss: {loss.item()}')


Epoch: 1 , Loss: 3.3725901362663055
Epoch: 2 , Loss: 3.24013894618684
Epoch: 3 , Loss: 3.101715420799648
Epoch: 4 , Loss: 2.9568015062436697
Epoch: 5 , Loss: 2.8100232866236046
Epoch: 6 , Loss: 2.662646251221915
Epoch: 7 , Loss: 2.5140264981596485
Epoch: 8 , Loss: 2.3646721391038734
Epoch: 9 , Loss: 2.212441287965667
Epoch: 10 , Loss: 2.0628746734610157
Epoch: 11 , Loss: 1.9192760794928871
Epoch: 12 , Loss: 1.7793701023983726
Epoch: 13 , Loss: 1.6448639423335791
Epoch: 14 , Loss: 1.516145147682461
Epoch: 15 , Loss: 1.39730397946741
Epoch: 16 , Loss: 1.28927708949492
Epoch: 17 , Loss: 1.1952641813251317
Epoch: 18 , Loss: 1.1142542961777822
Epoch: 19 , Loss: 1.0456366819188276
Epoch: 20 , Loss: 0.9897836048539858
Epoch: 21 , Loss: 0.9448348031493398
Epoch: 22 , Loss: 0.9086934874496816
Epoch: 23 , Loss: 0.8793750591347793
Epoch: 24 , Loss: 0.8552147841513313
Epoch: 25 , Loss: 0.8349275993408064
Epoch: 26 , Loss: 0.8175745637824564
Epoch: 27 , Loss: 0.8024917527794581
Epoch: 28 , Loss: 0.

# **Model Evaluation**

In [ ]:
from sklearn.metrics import accuracy_score
with torch.no_grad():
  acc=accuracy_score(y_test_tensor,y_pred=model.forward(X_test_tensor).round())
  print(acc)

0.5263157894736842
