<a href="https://colab.research.google.com/github/Huzaifa3242/Deep-Learning-Practice/blob/main/Pytorch_pipelining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [7]:
df.drop(["id","Unnamed: 32"],inplace=True,axis=1)

In [8]:
df.shape

(569, 31)

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [10]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
X_train

array([[ 0.08712109,  1.94792607,  0.16373436, ...,  0.81300909,
         2.22633217,  2.71567425],
       [-0.88248551, -0.11685149, -0.78787837, ...,  2.02466696,
         2.11838448,  3.05326621],
       [-0.21272835, -1.24761946, -0.21845411, ...,  0.25045364,
         0.55482963,  0.49192331],
       ...,
       [-0.11464676,  1.22489834, -0.01497226, ...,  0.52800089,
         1.26998309,  1.85535924],
       [-0.12865841,  0.70337013, -0.084018  , ...,  0.7548137 ,
         0.30688728,  0.49573483],
       [ 1.58636829,  0.22214184,  1.53530763, ...,  0.66528233,
        -0.58874122,  0.38846771]])

In [ ]:
Y_train

45     M
2      M
420    B
351    M
432    M
      ..
362    B
366    M
201    M
288    B
374    B
Name: diagnosis, Length: 455, dtype: object

In [12]:
encoder=LabelEncoder()
Y_train=encoder.fit_transform(Y_train)
Y_test=encoder.transform(Y_test)

In [ ]:
Y_train

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(Y_train)
y_test_tensor = torch.from_numpy(Y_test)

In [ ]:
X_train_tensor

tensor([[ 1.3024, -0.3797,  1.3319,  ...,  1.8924,  1.4627,  0.4161],
        [ 1.6001,  0.4854,  1.5944,  ...,  1.9722,  1.1628,  0.1854],
        [-0.7240, -0.0384, -0.7308,  ..., -0.7334,  0.2309, -0.0706],
        ...,
        [ 0.9847,  0.0280,  0.9735,  ...,  1.2189,  0.0584, -0.2959],
        [-0.8127,  0.1796, -0.7508,  ..., -0.3269,  0.1019, -0.7594],
        [-0.1172, -0.7423, -0.1625,  ..., -0.6839,  0.6952, -0.3856]],
       dtype=torch.float64)

**Model definition**

In [14]:
class PytorchNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out


  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

  #   # Calculate loss
  #   loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
  #   return loss






In [15]:
learning_rate=0.1
epochs=30

In [25]:
# define loss function
loss_func=nn.BCELoss()

**Training Pipeline**

In [36]:
# model creation
model=PytorchNN(X_train_tensor.shape[1])

# defining the optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(epochs):

  # forward pass
  y_pred=model(X_train_tensor.float())

  # loss calculate
  loss= loss_func(y_pred,y_train_tensor.float().view(-1,1))

  # making grad 0
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # updating params
  # with torch.no_grad():
  #   model.linear.weight-=learning_rate*model.linear.weight.grad
  #   model.linear.bias-=learning_rate*model.linear.bias.grad

  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  optimizer.step()

  print(f'Epoch: {epoch + 1} , Loss: {loss.item()}')


Epoch: 1 , Loss: 1.1004040241241455
Epoch: 2 , Loss: 0.7305618524551392
Epoch: 3 , Loss: 0.5361827611923218
Epoch: 4 , Loss: 0.43736732006073
Epoch: 5 , Loss: 0.37834110856056213
Epoch: 6 , Loss: 0.3384302258491516
Epoch: 7 , Loss: 0.3092620372772217
Epoch: 8 , Loss: 0.2867983281612396
Epoch: 9 , Loss: 0.2688342332839966
Epoch: 10 , Loss: 0.25405558943748474
Epoch: 11 , Loss: 0.24162611365318298
Epoch: 12 , Loss: 0.23098622262477875
Epoch: 13 , Loss: 0.22174595296382904
Epoch: 14 , Loss: 0.21362438797950745
Epoch: 15 , Loss: 0.2064136266708374
Epoch: 16 , Loss: 0.199956014752388
Epoch: 17 , Loss: 0.19412969052791595
Epoch: 18 , Loss: 0.18883872032165527
Epoch: 19 , Loss: 0.1840064525604248
Epoch: 20 , Loss: 0.17957082390785217
Epoch: 21 , Loss: 0.1754809021949768
Epoch: 22 , Loss: 0.17169451713562012
Epoch: 23 , Loss: 0.16817636787891388
Epoch: 24 , Loss: 0.1648966521024704
Epoch: 25 , Loss: 0.16183002293109894
Epoch: 26 , Loss: 0.15895472466945648
Epoch: 27 , Loss: 0.15625201165676117

# **Model Evaluation**

In [37]:
from sklearn.metrics import accuracy_score
with torch.no_grad():
  # Convert X_test_tensor to float32 to match the model's weight type
  acc=accuracy_score(y_test_tensor,y_pred=model.forward(X_test_tensor.float()).round())
  print(acc)

0.9473684210526315
